### PR TITLE
Bump lodash from 4.17.20 to 4.17.21

### PR DESCRIPTION
**Pull request by jportner**

### CODE REVIEW

**Review by watson — APPROVED** [review]
LGTM 👍

Side-note: lock files has no effect on modules distributed via npm - here the semver in `package.json` reigns supreme. I never recommend checking in the lock file to git for projects that distributed as npm packages as it gives a false sense of security. On top of that, your CI will run with a different set of dependencies than all your users, in which case your really not testing much 😅

**Comment by jportner** [comment]
Ah! In that case I removed the package-lock.json in 88eced8. Good?

**Review by watson — APPROVED** [review]
That sounds good as well 👍

The reason why I haven't done so previously was because this project used to be cloned down to users machines who ran `npm install` manually, in which case the lock file _is_ used. And I'm not sure if our small user-group have/will fully switched to using it via npm 🤷

**Review by watson — CHANGES_REQUESTED** [review]
Actually, I suggest we add an `.npmrc` file with the following content as well if we go down this route:

```
package-lock=false
```

**Review by watson — APPROVED** [review]

**Pull request merged**
